version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    #networks:
      #- internal

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 15s
      retries: 2

  cars-service-lab2:
    build: app_flask/services/carsService
    #image: ondubovickaya/cars-service-lab2
    container_name: cars-service-lab2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8070:8070"
    #networks:
      #- internal

  payments-service-lab2:
    build: app_flask/services/paymentService
    #image: ondubovickaya/payments-service-lab2
    container_name: payments-service-lab2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8050:8050"
    #networks:
      #- internal

  rental-service-lab2:
    build: app_flask/services/rentalService
    #image: ondubovickaya/rental-service-lab2
    container_name: rental-service-lab2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8060:8060"
    #networks:
      #- internal

  api-gateway-lab2:
    build: app_flask/services/gatewayService
    #image: ondubovickaya/api-gateway-lab2
    container_name: api-gateway-lab2
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CARS_SERVICE_HOST: "cars-service-lab2"
      CARS_SERVICE_PORT: "8070"
      PAYMENT_SERVICE_HOST: "payments-service-lab2"
      PAYMENT_SERVICE_PORT: "8050"
      RENTAL_SERVICE_HOST: "rental-service-lab2"
      RENTAL_SERVICE_PORT: "8060"
    ports:
      - "8080:8080"
    #networks:
      #- internal
    
volumes:
  db-data:

#networks:
  #internal:
